version: "3"
services:
  influxdb:
    build:
      context: .
      dockerfile: Dockerfile.influxdb
    ports:
      - "8086:8086"
  grafana:
    build:
      context: .
      dockerfile: Dockerfile.grafana
    links:
      - influxdb
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    ports:
      - "3000:3000"
  k6:
    image: loadimpact/k6:latest
    # remove below if you wanna run docker network
    network_mode: host
    ports:
      - "6565:6565"
    volumes:
      - "./tests:/tests"
      - "./dist:/dist"

    environment:
      - K6_OUT=${K6_OUT}
      - K6_CLOUD_TOKEN=${K6_CLOUD_TOKEN}
